[package]
name = "_socha"
version = "3.3.0"
edition = "2021"

[lib]
name = "socha"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.0" }
pyo3-log = "0.10.0"
log = "0.4.20"

[features]
extension-module = ["pyo3/extension-module"]
